# Generated by Django 3.0 on 2022-08-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220610_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='images',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='profiles/'),
        ),
    ]
