# Generated by Django 3.0 on 2022-08-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profiles_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='images',
        ),
    ]
