# Generated by Django 3.0 on 2022-08-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(default=None, max_length=250, null=True, upload_to='images/')),
            ],
        ),
    ]
